/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcxiaoke_demo_boost_BoostDemo */

#ifndef _Included_com_mcxiaoke_demo_boost_BoostDemo
#define _Included_com_mcxiaoke_demo_boost_BoostDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcxiaoke_demo_boost_BoostDemo
 * Method:    boostDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mcxiaoke_demo_boost_BoostDemo_boostDate
  (JNIEnv *, jobject);

/*
 * Class:     com_mcxiaoke_demo_boost_BoostDemo
 * Method:    boostIO
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mcxiaoke_demo_boost_BoostDemo_boostIO
  (JNIEnv *, jobject);

/*
 * Class:     com_mcxiaoke_demo_boost_BoostDemo
 * Method:    boostFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mcxiaoke_demo_boost_BoostDemo_boostFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
